### ISSUE TITLE
Is there a setup guide on osx?

### ISSUE THREAD

**Issue by mrkaspa** [konovod/linalg#1]

**Comment by konovod** [comment]
Looks like there is no easy way to install LAPACK**E** on OSX, so 
- either compile lapacke from sources
- or wait because I plan to drop lapacke dependency (it provides work buffers allocation and column-major vs row-major order but both in not a best way).

**Comment by mrkaspa** [comment]
@konovod great I'll wait for it

**Comment by konovod** [comment]
It takes less than a year!
Now `lapacke` dependency is dropped and it works on OSX without any additional setup (it uses Apple Accelerate framework) .
There are still two spec failures: https://travis-ci.org/konovod/linalg/jobs/411752616 and i'll investigate them, but i think it's a problem of specs, not a library.
