### ISSUE TITLE
Pseudo Inverse of matrices

### ISSUE THREAD

**Issue by RainbowZephyr** [konovod/linalg#17]
Hello,
First and foremost, great library we use it in production in some of our apps and has been going great so far.  Regarding the future roadmap, you state that you wish to add Pseudo Inverse of matrices at some point. Is the pseudo inverse a dedicated call to LAPACK? Because we have implemented in pure Crystal using what we can call from the available APIs at this point and could create a merge request for it.

Keep up the great job

**Comment by konovod** [comment]
Thank you!
Funny that I've thought about pseudoinverse (and lack of it in a library) few days ago.
I think there is no single function in LAPACK that does pinv, so if your implementation use SVD decomposition and then multiplications, then basically it's same way i would implement it. So PR would be great!

**Comment by RainbowZephyr** [comment]
Sorry for the late reply, yes I do use that method I will initiate a PR once I add it to a branch.

Have a great day :smile:

**Comment by konovod** [comment]
Closed by #18
