### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by RainbowZephyr** [konovod/linalg#19]
Hello, 
Whenever I run `shards install`, it keeps installing an old version of the library specifically the one with commit `07a59a0aa444568aefef23eb914a457e1d38d2c5` from December of 2022. I don't know what needs to be done but a version bump may help?

Thanks in advance

**Comment by konovod** [comment]
Hello!
I've bumped version and added a release for 0.3.0, please check if this helps.
If this doesn't help, `shards` caches downloaded shards in `.shards` folder, so maybe you should delete it.

**Comment by RainbowZephyr** [comment]
Deleting the .shards folder + shards.lock worked.

Thank you
